apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-argo
  template:
    metadata:
      labels:
        app: nginx-argo
    spec:
      containers:
        - name: nginx-argo
          image: nginx:latest
          ports:
            - containerPort: 80
 
